[package]
name = "rlox"
version = "0.1.0"
authors = ["Sean McLoughlin <smcloughlin1015@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.22"
strum = "0.20.0"
strum_macros = "0.20.0"